app = "samplemongodb"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  PORT = "27017"
[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  internal_port = 27017
  processes = ["app"]
  protocol = "tcp"
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    port = 27017

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
[[mounts]]
    destination = "/var/lib/mongodb"
    source = "productiondb_storage"
